version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana_network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb


  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - grafana_network
    volumes:
      - influxdb_data:/var/lib/influxdb2
      
    environment:
      #- INFLUXDB_DB=grafana
      #- INFLUXDB_USER=grafana
      #- INFLUXDB_USER_PASSWORD=grafanapass
      #- INFLUXDB_ADMIN_ENABLED=true
      #- INFLUXDB_ADMIN_USER=admin 
      #- INFLUXDB_ADMIN_PASSWORD=1D3nt1d@d301 

      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=1D3nt1d@d301
      - DOCKER_INFLUXDB_INIT_ORG=hass 
      - DOCKER_INFLUXDB_INIT_BUCKET=grafana
     

networks:
  grafana_network:
volumes:
  grafana_data:
  influxdb_data:
