version: '3.3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=1D3nt1d@d301
      - DOCKER_INFLUXDB_INIT_ORG=spadora
      - DOCKER_INFLUXDB_INIT_BUCKET=hass

volumes:
    influxdb-storage: